# https://taskfile.dev

version: '3'

vars:
  BIN: dojo

tasks:
  default:
    cmds:
      - task: build
      - task: run
  build:
    cmds:
      - go build -o {{.BIN}}
  run:
    cmds:
      - ./{{.BIN}}
  clean:
    cmds:
      - rm ./{{.BIN}}
