# https://taskfile.dev

version: '3'

vars:
  BIN: dojo
  MAIN: dojo.go

tasks:
  default:
    cmds:
      - task: build
      - task: exec
  run:
    cmds:
      - go run {{.MAIN}}
  build:
    cmds:
      - go build -o {{.BIN}}
  exec:
    cmds:
      - ./{{.BIN}}
  clean:
    cmds:
      - rm ./{{.BIN}}
